version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - TZ=Africa/Luanda
    ports:
      - "4500:80"
      - "6000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - mynetwork

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Africa/Luanda
    ports:
      - "5000:80"
      - "7000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - redis
      - rabbitmq-server
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  rabbitmq-server:
    image: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port for AMQP
      - "15672:15672"  # RabbitMQ Management UI port
    networks:
      - mynetwork

networks:
  mynetwork:
